#############################################################################
# Makefile for building: StationPage
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  StationPage.pro
# Template: app
# Command: /opt/qtrpi/bin/qmake-qtrpi -o Makefile StationPage.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc
CXX           = /opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -pipe -Os -mthumb -mfloat-abi=hard --sysroot=/opt/qtrpi/raspbian/sysroot -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -march=armv8-a+crc -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -pipe -Os -mthumb -std=c++11 -mfloat-abi=hard --sysroot=/opt/qtrpi/raspbian/sysroot -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/qtrpi/raspbian/sysroot/opt/vc/include -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos/pthreads -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vmcs_host/linux -I/opt/qtrpi/raspi/qt5pi/include -I/opt/qtrpi/raspi/qt5pi/include/QtCharts -I/opt/qtrpi/raspi/qt5pi/include/QtWidgets -I/opt/qtrpi/raspi/qt5pi/include/QtQuick -I/opt/qtrpi/raspi/qt5pi/include/QtGui -I/opt/qtrpi/raspi/qt5pi/include/QtQml -I/opt/qtrpi/raspi/qt5pi/include/QtNetwork -I/opt/qtrpi/raspi/qt5pi/include/QtCore -I. -I=/opt/vc/include -I=/opt/vc/include/interface/vcos/pthreads -I=/opt/vc/include/interface/vmcs_host/linux -I/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++
QMAKE         = /opt/qtrpi/bin/qmake-qtrpi
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = StationPage1.0.0
DISTDIR = /home/tam/Workspace/StationPage/.tmp/StationPage1.0.0
LINK          = /opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-rpath-link,/opt/qtrpi/raspbian/sysroot/opt/vc/lib -Wl,-rpath-link,/opt/qtrpi/raspbian/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/opt/qtrpi/raspbian/sysroot/lib/arm-linux-gnueabihf -mfloat-abi=hard --sysroot=/opt/qtrpi/raspbian/sysroot -Wl,-O1 -Wl,-rpath,/usr/local/qt5pi/lib
LIBS          = $(SUBLIBS) -L=/opt/vc/lib -L/opt/qtrpi/raspi/qt5pi/lib -lQt5Charts -L/opt/qtrpi/raspbian/sysroot/usr/lib/arm-linux-gnueabihf -lQt5Widgets -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -Wl,-rpath-link,/opt/qtrpi/raspbian/sysroot/opt/vc/lib -lGLESv2 -lpthread 
AR            = /opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp \
		moc_main.cpp
OBJECTS       = main.o \
		qrc_qml.o \
		moc_main.o
DIST          = /opt/qtrpi/raspi/qt5/mkspecs/features/spec_pre.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/unix.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/linux.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/sanitize.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/gcc-base.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/g++-base.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/g++-unix.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/qdevice.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/features/device_config.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/qconfig.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_charts.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/features/qt_functions.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/qt_config.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++/qmake.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qtrpi/raspi/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/default_pre.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/resolve_config.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/default_post.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/warn_on.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/qt.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/resources.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/moc.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/unix/opengl.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/uic.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/unix/thread.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/file_copies.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/testcase_targets.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/exceptions.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/yacc.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/lex.prf \
		StationPage.pro main.h main.cpp
QMAKE_TARGET  = StationPage
DESTDIR       = 
TARGET        = StationPage


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: StationPage.pro /opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++/qmake.conf /opt/qtrpi/raspi/qt5/mkspecs/features/spec_pre.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/unix.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/linux.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/sanitize.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/gcc-base.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/g++-base.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/common/g++-unix.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/qdevice.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/features/device_config.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/qconfig.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_charts.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qtrpi/raspi/qt5/mkspecs/features/qt_functions.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/qt_config.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++/qmake.conf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qtrpi/raspi/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/default_pre.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/resolve_config.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/default_post.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/warn_on.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/qt.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/resources.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/moc.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/unix/opengl.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/uic.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/unix/thread.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/file_copies.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/testcase_targets.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/exceptions.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/yacc.prf \
		/opt/qtrpi/raspi/qt5/mkspecs/features/lex.prf \
		StationPage.pro \
		qml.qrc \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5Charts.prl \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5Widgets.prl \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5Quick.prl \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5Gui.prl \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5Qml.prl \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5Network.prl \
		/opt/qtrpi/raspi/qt5pi/lib/libQt5Core.prl
	$(QMAKE) -o Makefile StationPage.pro
/opt/qtrpi/raspi/qt5/mkspecs/features/spec_pre.prf:
/opt/qtrpi/raspi/qt5/mkspecs/common/unix.conf:
/opt/qtrpi/raspi/qt5/mkspecs/common/linux.conf:
/opt/qtrpi/raspi/qt5/mkspecs/common/sanitize.conf:
/opt/qtrpi/raspi/qt5/mkspecs/common/gcc-base.conf:
/opt/qtrpi/raspi/qt5/mkspecs/common/gcc-base-unix.conf:
/opt/qtrpi/raspi/qt5/mkspecs/common/g++-base.conf:
/opt/qtrpi/raspi/qt5/mkspecs/common/g++-unix.conf:
/opt/qtrpi/raspi/qt5/mkspecs/qdevice.pri:
/opt/qtrpi/raspi/qt5/mkspecs/features/device_config.prf:
/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_device_pre.conf:
/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_device_post.conf:
/opt/qtrpi/raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf:
/opt/qtrpi/raspi/qt5/mkspecs/qconfig.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3drender.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_charts.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/qtrpi/raspi/qt5/mkspecs/features/qt_functions.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/qt_config.prf:
/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++/qmake.conf:
/opt/qtrpi/raspi/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/qtrpi/raspi/qt5/mkspecs/features/exclusive_builds.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/default_pre.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/resolve_config.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/default_post.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/warn_on.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/qt.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/resources.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/moc.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/unix/opengl.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/uic.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/unix/thread.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/file_copies.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/testcase_targets.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/exceptions.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/yacc.prf:
/opt/qtrpi/raspi/qt5/mkspecs/features/lex.prf:
StationPage.pro:
qml.qrc:
/opt/qtrpi/raspi/qt5pi/lib/libQt5Charts.prl:
/opt/qtrpi/raspi/qt5pi/lib/libQt5Widgets.prl:
/opt/qtrpi/raspi/qt5pi/lib/libQt5Quick.prl:
/opt/qtrpi/raspi/qt5pi/lib/libQt5Gui.prl:
/opt/qtrpi/raspi/qt5pi/lib/libQt5Qml.prl:
/opt/qtrpi/raspi/qt5pi/lib/libQt5Network.prl:
/opt/qtrpi/raspi/qt5pi/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile StationPage.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents main.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		/opt/qtrpi/raspi/qt5/bin/rcc \
		StationPage.qml \
		ControlPanel.qml \
		Page1.qml \
		qtquickcontrols2.conf \
		main.qml
	/opt/qtrpi/raspi/qt5/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_main.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main.cpp
moc_main.cpp: /opt/qtrpi/raspi/qt5pi/include/QtWidgets/QApplication \
		/opt/qtrpi/raspi/qt5pi/include/QtWidgets/qapplication.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreapplication.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qeventloop.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qwindowdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsize.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qcursor.h \
		/opt/qtrpi/raspi/qt5pi/include/QtWidgets/qdesktopwidget.h \
		/opt/qtrpi/raspi/qt5pi/include/QtWidgets/qwidget.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmargins.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpaintdevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrect.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpalette.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qcolor.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qrgb.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qrgba64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qbrush.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qmatrix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpolygon.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qregion.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qline.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qtransform.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpainterpath.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qimage.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpixelformat.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpixmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qfont.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qfontmetrics.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qfontinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qkeysequence.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qurl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qurlquery.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qvector2d.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qtouchdevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qguiapplication.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qinputmethod.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/QGuiApplication \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/QQmlApplicationEngine \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlapplicationengine.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlengine.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qjsengine.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qjsvalue.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qtqmlglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqml.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlprivate.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlparserstatus.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlpropertyvaluesource.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmllist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetaobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlerror.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmldebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/QQmlContext \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlcontext.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QList \
		main.h \
		/opt/qtrpi/raspi/qt5/bin/moc
	/opt/qtrpi/raspi/qt5/bin/moc $(DEFINES) -I/opt/qtrpi/raspi/qt5/mkspecs/devices/linux-rpi3-g++ -I/home/tam/Workspace/StationPage -I/opt/qtrpi/raspbian/sysroot/opt/vc/include -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vcos/pthreads -I/opt/qtrpi/raspbian/sysroot/opt/vc/include/interface/vmcs_host/linux -I/opt/qtrpi/raspi/qt5pi/include -I/opt/qtrpi/raspi/qt5pi/include/QtCharts -I/opt/qtrpi/raspi/qt5pi/include/QtWidgets -I/opt/qtrpi/raspi/qt5pi/include/QtQuick -I/opt/qtrpi/raspi/qt5pi/include/QtGui -I/opt/qtrpi/raspi/qt5pi/include/QtQml -I/opt/qtrpi/raspi/qt5pi/include/QtNetwork -I/opt/qtrpi/raspi/qt5pi/include/QtCore -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3 -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/opt/qtrpi/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -I/opt/qtrpi/raspbian/sysroot/usr/include -I/opt/qtrpi/raspbian/sysroot/usr/include/arm-linux-gnueabihf main.h -o moc_main.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp main.h \
		/opt/qtrpi/raspi/qt5pi/include/QtWidgets/QApplication \
		/opt/qtrpi/raspi/qt5pi/include/QtWidgets/qapplication.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreapplication.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qconfig.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfeatures.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtypetraits.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qisenum.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlogging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qflags.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmutex.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnumeric.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstring.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qchar.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrefcount.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qnamespace.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qarraydata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiterator.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpair.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringlist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qregexp.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetatype.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qeventloop.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qwindowdefs.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qpoint.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsize.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qcursor.h \
		/opt/qtrpi/raspi/qt5pi/include/QtWidgets/qdesktopwidget.h \
		/opt/qtrpi/raspi/qt5pi/include/QtWidgets/qwidget.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmargins.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpaintdevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qrect.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpalette.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qcolor.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qrgb.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qrgba64.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qbrush.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvector.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qmatrix.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpolygon.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qregion.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdatastream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qiodevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qline.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qtransform.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpainterpath.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qimage.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpixelformat.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qpixmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qshareddata.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qhash.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qfont.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qfontmetrics.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qfontinfo.h \
		/opt/qtrpi/raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qkeysequence.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qevent.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qvariant.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmap.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qdebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qtextstream.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qlocale.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qset.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qurl.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qurlquery.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfile.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qfiledevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qvector2d.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qtouchdevice.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qguiapplication.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/qinputmethod.h \
		/opt/qtrpi/raspi/qt5pi/include/QtGui/QGuiApplication \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/QQmlApplicationEngine \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlapplicationengine.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlengine.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qjsengine.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qjsvalue.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qtqmlglobal.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqml.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlprivate.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlparserstatus.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlpropertyvaluesource.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmllist.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/qmetaobject.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlerror.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmldebug.h \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/QQmlContext \
		/opt/qtrpi/raspi/qt5pi/include/QtQml/qqmlcontext.h \
		/opt/qtrpi/raspi/qt5pi/include/QtCore/QList
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_main.o: moc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main.o moc_main.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/StationPage/bin || mkdir -p $(INSTALL_ROOT)/opt/StationPage/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/StationPage/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/StationPage/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/StationPage/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/StationPage/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

